### ISSUE TITLE
how

### ISSUE THREAD

**Issue by Bigmike66** [fail0verflow/ps4-radeon-patches#1]
can you make a tutorial please

**Comment by CuriousTommy** [comment]
### First Off

One thing for sure, you are going to need to manually compile with the patches applied to libdrm, mesa, and xf86-video-ati.
Also, I am not sure if you are able to compile this outside of Linux. So you might need a Linux machine to compile this program.

### Where to find the software

You can find them here:

| Software | Website |
| --- | --- |
| Mesa | [mesa3d.org](http://www.mesa3d.org/download.html) |
| libdrm | [cgit.freedesktop.org](https://cgit.freedesktop.org/mesa/drm) |
| xf86-video-ati | [cgit.freedesktop.org](https://cgit.freedesktop.org/xorg/driver/xf86-video-ati/) |

Be sure to read up on what software you need in order to compile these software!

### How to apply patches

The [cyberciti.biz](http://www.cyberciti.biz/faq/appy-patch-file-using-patch-command/) website has a good explanation on how to apply patches.

> To apply a patch, one could run the following command in a shell:
> 
> ```
> $ patch < /path/to/file
> ```
> 
> In this example, patch foo.c with patch.diff file:
> 
> ```
> $ patch foo.c < patch.diff
> ```
